export const PRESETS = [
  {
    id: 'diml-13-beats',
    name: '☕ 13-Beat Storyboard',
    tag: 'Full Day Reel',
    description: 'Complete 36.0s 13-beat Day in My Life vlog storyboard from 07:00 AM to 11:11 PM',
    config: {
      duration: 36.0,
      timelineMode: 'keyframes',
      digitGrouping: 'paired',
      rollMode: 'ultra-smooth',
      smoothness: 1.0,
      minuteStyle: 'interval-15m',
      minuteSpeed: 0.75,
      motionBlur: true,
      timeFormat: '24h',
      keyframeTransitionDuration: 1.0,
      keyframeTransitionPlacement: 'arrive',
      keyframeSpinDynamic: 'direct',
      minuteCadence: 'quarters',
      customMilestones: '0, 15, 30, 45',
      fontFamily: 'Unbounded',
      fontSize: 150,
      textColor: '#FFFFFF',
      glowColor: '#00F5FF',
      glowIntensity: 0.55,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(0, 245, 255, 0.4)',
      tagline: 'DAY IN MY LIFE',
      taglineColor: '#00F5FF',
      drumShadow: true,
      digitSpacing: -12,
      colonStyle: 'pulse',
      keyframes: [
        { id: 'kf_1', videoTimeStr: '00:00.01', videoTimeSec: 0.0, hour: 7, minute: 0, tagline: 'WAKE UP' },
        { id: 'kf_2', videoTimeStr: '00:03.11', videoTimeSec: 3.18, hour: 7, minute: 15, tagline: 'GUM' },
        { id: 'kf_3', videoTimeStr: '00:04.48', videoTimeSec: 4.80, hour: 7, minute: 30, tagline: '' },
        { id: 'kf_4', videoTimeStr: '00:09.42', videoTimeSec: 9.68, hour: 7, minute: 50, tagline: '' },
        { id: 'kf_5', videoTimeStr: '00:12.21', videoTimeSec: 12.33, hour: 8, minute: 0, tagline: '' },
        { id: 'kf_6', videoTimeStr: '00:14.44', videoTimeSec: 14.73, hour: 12, minute: 30, tagline: '' },
        { id: 'kf_7', videoTimeStr: '00:16.57', videoTimeSec: 16.93, hour: 13, minute: 15, tagline: '' },
        { id: 'kf_8', videoTimeStr: '00:19.11', videoTimeSec: 19.17, hour: 13, minute: 30, tagline: '' },
        { id: 'kf_9', videoTimeStr: '00:22.08', videoTimeSec: 22.12, hour: 18, minute: 0, tagline: '' },
        { id: 'kf_10', videoTimeStr: '00:23.30', videoTimeSec: 23.48, hour: 18, minute: 30, tagline: '' },
        { id: 'kf_11', videoTimeStr: '00:26.15', videoTimeSec: 26.23, hour: 19, minute: 30, tagline: '' },
        { id: 'kf_12', videoTimeStr: '00:28.04', videoTimeSec: 28.05, hour: 21, minute: 0, tagline: '' },
        { id: 'kf_13', videoTimeStr: '00:32.20', videoTimeSec: 32.32, hour: 23, minute: 11, tagline: '' }
      ]
    }
  },
  {
    id: 'unbounded-wide',
    name: 'Unbounded Wide',
    tag: 'Trending Reel',
    description: 'Ultra-wide geometric aesthetic font with negative spacing for modern reels',
    config: {
      fontFamily: 'Unbounded',
      fontSize: 145,
      textColor: '#FFFFFF',
      glowColor: '#00F5FF',
      glowIntensity: 0.5,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(0, 245, 255, 0.4)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'DAY IN MY LIFE',
      taglineColor: '#00F5FF',
      drumShadow: true,
      digitSpacing: -12, // Tucked tight!
      colonStyle: 'pulse'
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    tag: 'High Voltage',
    description: 'Electric cyan core with vibrant magenta-blue atmospheric bloom',
    config: {
      fontFamily: 'Orbitron',
      fontSize: 160,
      textColor: '#00F5FF',
      glowColor: '#FF007F',
      glowIntensity: 0.85,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'neon-capsule',
      borderColor: 'rgba(0, 245, 255, 0.4)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'DAY IN MY LIFE',
      taglineColor: '#00F5FF',
      drumShadow: true,
      digitSpacing: 14,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'syne-editorial',
    name: 'Syne Broad Luxe',
    tag: 'Broad & Clean',
    description: 'Bold editorial heavyweight typography with tight negative spacing',
    config: {
      fontFamily: 'Syne',
      fontSize: 155,
      textColor: '#FFFFFF',
      glowColor: '#FFFFFF',
      glowIntensity: 0.3,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'minimal-pill',
      borderColor: 'rgba(255, 255, 255, 0.25)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: '24 HOURS',
      taglineColor: 'rgba(255, 255, 255, 0.8)',
      drumShadow: true,
      digitSpacing: -16,
      colonStyle: 'steady'
    }
  },
  {
    id: 'comfortaa-round',
    name: 'Comfortaa Round',
    tag: 'Smooth Curves',
    description: 'Soft rounded geometric curves with cozy sunset amber glow',
    config: {
      fontFamily: 'Comfortaa',
      fontSize: 150,
      textColor: '#FFE7B8',
      glowColor: '#FF8844',
      glowIntensity: 0.65,
      bgType: 'transparent',
      bgColor: '#100703',
      frameStyle: 'neon-capsule',
      borderColor: 'rgba(255, 136, 68, 0.35)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'MY MORNING ROUTINE',
      taglineColor: '#FFE7B8',
      drumShadow: true,
      digitSpacing: -8,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'holly-berry-pop',
    name: '🍓 Holly Berry Pop',
    tag: 'Bubbly Aesthetic',
    description: 'Charming bubbly rounded typography with berry pink glow for cute lifestyle reels',
    config: {
      fontFamily: 'Holly Berry Pop',
      fontSize: 155,
      textColor: '#FFFFFF',
      glowColor: '#FF2A85',
      glowIntensity: 0.65,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(255, 42, 133, 0.45)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'A DAY IN MY LIFE ♡',
      taglineColor: '#FF2A85',
      drumShadow: true,
      digitSpacing: -8,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'minimal-white',
    name: 'Minimalist Luxe',
    tag: 'Clean & Aesthetic',
    description: 'Ultra-clean pristine white typography with soft frosted glass backing',
    config: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 165,
      textColor: '#FFFFFF',
      glowColor: '#FFFFFF',
      glowIntensity: 0.25,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(255, 255, 255, 0.18)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'A DAY WITH ME',
      taglineColor: 'rgba(255, 255, 255, 0.7)',
      drumShadow: true,
      digitSpacing: -10,
      colonStyle: 'steady'
    }
  },
  {
    id: 'retro-vcr',
    name: 'Retro 80s VCR',
    tag: 'Vintage Odometer',
    description: 'Phosphor green digital meter drum with authentic mechanical styling',
    config: {
      fontFamily: 'VT323',
      fontSize: 200,
      textColor: '#39FF14',
      glowColor: '#00FF44',
      glowIntensity: 0.7,
      bgType: 'solid',
      bgColor: '#0a100a',
      frameStyle: 'odometer-bezel',
      borderColor: '#39FF14',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: false,
      timeFormat: '24h',
      showSeconds: true,
      tagline: 'REC ● PLAY',
      taglineColor: '#39FF14',
      drumShadow: true,
      digitSpacing: 8,
      colonStyle: 'blink'
    }
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour Sunset',
    tag: 'Warm Amber',
    description: 'Warm glowing sunlight tones for aesthetic lifestyle & travel vlogs',
    config: {
      fontFamily: 'Kanit',
      fontSize: 175,
      textColor: '#FFB800',
      glowColor: '#FF5E00',
      glowIntensity: 0.75,
      bgType: 'transparent',
      bgColor: '#120800',
      frameStyle: 'minimal-pill',
      borderColor: 'rgba(255, 184, 0, 0.35)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'GOLDEN ROUTINE',
      taglineColor: '#FFB800',
      drumShadow: true,
      digitSpacing: -14,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'chroma-green',
    name: 'Chroma Key Green (CapCut Ready)',
    tag: '1-Click Overlay',
    description: 'Crisp white digits against pure #00FF00 for instant chroma key removal',
    config: {
      fontFamily: 'Unbounded',
      fontSize: 150,
      textColor: '#FFFFFF',
      glowColor: '#00FFFF',
      glowIntensity: 0.5,
      bgType: 'greenscreen',
      bgColor: '#00FF00',
      frameStyle: 'none',
      borderColor: 'transparent',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: '',
      taglineColor: '#FFFFFF',
      drumShadow: false,
      digitSpacing: -12,
      colonStyle: 'steady'
    }
  }
];
