export const PRESETS = [
  {
    id: 'unbounded-wide',
    name: 'Unbounded Wide',
    tag: 'Trending Reel',
    description: 'Ultra-wide geometric aesthetic font with negative spacing for modern reels',
    config: {
      fontFamily: 'Unbounded',
      fontSize: 145,
      textColor: '#FFFFFF',
      glowColor: '#00F5FF',
      glowIntensity: 0.5,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(0, 245, 255, 0.4)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'DAY IN MY LIFE',
      taglineColor: '#00F5FF',
      drumShadow: true,
      digitSpacing: -12, // Tucked tight!
      colonStyle: 'pulse'
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    tag: 'High Voltage',
    description: 'Electric cyan core with vibrant magenta-blue atmospheric bloom',
    config: {
      fontFamily: 'Orbitron',
      fontSize: 160,
      textColor: '#00F5FF',
      glowColor: '#FF007F',
      glowIntensity: 0.85,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'neon-capsule',
      borderColor: 'rgba(0, 245, 255, 0.4)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'DAY IN MY LIFE',
      taglineColor: '#00F5FF',
      drumShadow: true,
      digitSpacing: 14,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'syne-editorial',
    name: 'Syne Broad Luxe',
    tag: 'Broad & Clean',
    description: 'Bold editorial heavyweight typography with tight negative spacing',
    config: {
      fontFamily: 'Syne',
      fontSize: 155,
      textColor: '#FFFFFF',
      glowColor: '#FFFFFF',
      glowIntensity: 0.3,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'minimal-pill',
      borderColor: 'rgba(255, 255, 255, 0.25)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: '24 HOURS',
      taglineColor: 'rgba(255, 255, 255, 0.8)',
      drumShadow: true,
      digitSpacing: -16,
      colonStyle: 'steady'
    }
  },
  {
    id: 'comfortaa-round',
    name: 'Comfortaa Round',
    tag: 'Smooth Curves',
    description: 'Soft rounded geometric curves with cozy sunset amber glow',
    config: {
      fontFamily: 'Comfortaa',
      fontSize: 150,
      textColor: '#FFE7B8',
      glowColor: '#FF8844',
      glowIntensity: 0.65,
      bgType: 'transparent',
      bgColor: '#100703',
      frameStyle: 'neon-capsule',
      borderColor: 'rgba(255, 136, 68, 0.35)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'MY MORNING ROUTINE',
      taglineColor: '#FFE7B8',
      drumShadow: true,
      digitSpacing: -8,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'holly-berry-pop',
    name: '🍓 Holly Berry Pop',
    tag: 'Bubbly Aesthetic',
    description: 'Charming bubbly rounded typography with berry pink glow for cute lifestyle reels',
    config: {
      fontFamily: 'Holly Berry Pop',
      fontSize: 155,
      textColor: '#FFFFFF',
      glowColor: '#FF2A85',
      glowIntensity: 0.65,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(255, 42, 133, 0.45)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'A DAY IN MY LIFE ♡',
      taglineColor: '#FF2A85',
      drumShadow: true,
      digitSpacing: -8,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'minimal-white',
    name: 'Minimalist Luxe',
    tag: 'Clean & Aesthetic',
    description: 'Ultra-clean pristine white typography with soft frosted glass backing',
    config: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 165,
      textColor: '#FFFFFF',
      glowColor: '#FFFFFF',
      glowIntensity: 0.25,
      bgType: 'transparent',
      bgColor: '#000000',
      frameStyle: 'frosted-glass',
      borderColor: 'rgba(255, 255, 255, 0.18)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'A DAY WITH ME',
      taglineColor: 'rgba(255, 255, 255, 0.7)',
      drumShadow: true,
      digitSpacing: -10,
      colonStyle: 'steady'
    }
  },
  {
    id: 'retro-vcr',
    name: 'Retro 80s VCR',
    tag: 'Vintage Odometer',
    description: 'Phosphor green digital meter drum with authentic mechanical styling',
    config: {
      fontFamily: 'VT323',
      fontSize: 200,
      textColor: '#39FF14',
      glowColor: '#00FF44',
      glowIntensity: 0.7,
      bgType: 'solid',
      bgColor: '#0a100a',
      frameStyle: 'odometer-bezel',
      borderColor: '#39FF14',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: false,
      timeFormat: '24h',
      showSeconds: true,
      tagline: 'REC ● PLAY',
      taglineColor: '#39FF14',
      drumShadow: true,
      digitSpacing: 8,
      colonStyle: 'blink'
    }
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour Sunset',
    tag: 'Warm Amber',
    description: 'Warm glowing sunlight tones for aesthetic lifestyle & travel vlogs',
    config: {
      fontFamily: 'Kanit',
      fontSize: 175,
      textColor: '#FFB800',
      glowColor: '#FF5E00',
      glowIntensity: 0.75,
      bgType: 'transparent',
      bgColor: '#120800',
      frameStyle: 'minimal-pill',
      borderColor: 'rgba(255, 184, 0, 0.35)',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: 'GOLDEN ROUTINE',
      taglineColor: '#FFB800',
      drumShadow: true,
      digitSpacing: -14,
      colonStyle: 'pulse'
    }
  },
  {
    id: 'chroma-green',
    name: 'Chroma Key Green (CapCut Ready)',
    tag: '1-Click Overlay',
    description: 'Crisp white digits against pure #00FF00 for instant chroma key removal',
    config: {
      fontFamily: 'Unbounded',
      fontSize: 150,
      textColor: '#FFFFFF',
      glowColor: '#00FFFF',
      glowIntensity: 0.5,
      bgType: 'greenscreen',
      bgColor: '#00FF00',
      frameStyle: 'none',
      borderColor: 'transparent',
      rollMode: 'continuous',
      smoothness: 0.85,
      motionBlur: true,
      timeFormat: '24h',
      showSeconds: false,
      tagline: '',
      taglineColor: '#FFFFFF',
      drumShadow: false,
      digitSpacing: -12,
      colonStyle: 'steady'
    }
  }
];
